export const GET_ALL_DOGS = "GET_ALL_DOGS";
export const GET_DOGS_BYID = "GET_DOGS_BYID";
export const GET_DOGS_BY_NAMES = "GET_DOGS_BY_NAMES";
export const FILTER_DOGS_BY_TEMPERS = "FILTER_DOGS_BY_TEMPERS";
export const ORDER_DOGS = "ORDER_DOGS";
export const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN";
