export const GET_ALL_DOGS = "GET_ALL_DOGS";
export const GET_DOGS_BYID = "GET_DOGS_BYID";
export const GET_DOGS_BY_NAMES = "GET_DOGS_BY_NAMES";
export const GET_ALL_TEMPERS = "GET_ALL_TEMPERS";
export const FILTER_DOGS_BY_TEMPERS = "FILTER_DOGS_BY_TEMPERS";
